TVP_NAME="varnish"
TVP_DESC="Varnish HTTP cache"
TVP_CATEGORY="cache"
TVP_PORTS=(6081)
TVP_UI_PORT=""
TVP_UI_SUBDOMAIN=""
TVP_INSTALL_apt='apt-get update && apt-get install -y varnish && service varnish start'
TVP_INSTALL_apk='apk add varnish && rc-service varnish start'
TVP_INSTALL_dnf='dnf install -y varnish && systemctl start varnish'
TVP_INSTALL_zypper='zypper install -y varnish && systemctl start varnish'
TVP_INSTALL_pacman='pacman -S --noconfirm varnish && systemctl start varnish'
TVP_INSTALL_xbps='xbps-install -y varnish && ln -s /etc/sv/varnish /var/service/'
