# ============================================================
# tavpbox — LXD engine (box lifecycle, folder map, limits)
# ============================================================
source "${TVP_LIB}/services.sh"

# Run a command inside a box
tvp_box_exec() {
    local name="$1"; shift
    lxc exec "${name}" -- bash -c "$*"
}

tvp_box_ip() {
    local name="$1"
    if command -v jq >/dev/null 2>&1; then
        lxc list "${name}" --format json 2>/dev/null \
            | jq -r '.[0].state.network.eth0.addresses[]? | select(.family=="inet") | .address' \
            | head -1
    else
        lxc list "${name}" --format json 2>/dev/null \
            | grep -oE '"address": ?"[0-9.]+"' | head -1 | grep -oE '[0-9.]+'
    fi
}

tvp_box_dir() { echo "${TVP_STATE}/boxes/$1"; }

# ── init ─────────────────────────────────────────────────────
tvp_cmd_init() {
    tvp_step "Mendeteksi sistem..."
    local os; os="$(tvp_detect_os)"
    tvp_ok "OS: ${os}"

    if ! tvp_lxd_present; then
        tvp_error "LXD belum terpasang. Jalankan installer:"
        case "${os}" in
            linux) echo "    bash install/install-linux.sh" ;;
            wsl)   echo "    jalankan install/install-wsl.ps1 di PowerShell" ;;
            mac)   echo "    bash install/install-mac.sh" ;;
        esac
        exit 1
    fi

    tvp_step "Setup LXD (sekali)..."
    if ! lxc remote list 2>/dev/null | grep -q 'images:'; then
        lxc remote add images https://images.linuxcontainers.org --accept-certificate --public 2>/dev/null || true
    fi
    if ! lxc list >/dev/null 2>&1; then
        tvp_spin "lxd init --auto" lxd init --auto
    fi

    tvp_step "Pilih base distro (TUI)..."
    local choices=()
    for d in "${TVP_DISTROS[@]}"; do
        local key="${d%%|*}"; local rest="${d#*|}"; local label="${rest%%|*}"
        choices+=("${key}" "${label}")
    done
    choices+=("custom" "Lainnya... (ketik nama distro)")
    local distro
    distro="$(tvp_tui_select 'Base distro untuk box (default: ubuntu):' "${choices[@]}")"
    [ -z "${distro}" ] && distro="ubuntu"
    if [ "${distro}" = "custom" ]; then
        distro="$(tvp_tui_input 'Nama distro (misal: rocky):' '')"
    fi

    tvp_step "Domain suffix..."
    local domain
    domain="$(tvp_tui_input 'Domain suffix untuk box:' 'tavp.local')"
    [ -z "${domain}" ] && domain="tavp.local"

    tvp_step "Resource limit per box..."
    local ram cpu
    ram="$(tvp_tui_input 'RAM max per box (misal 512MB, 1GB):' '512MB')"
    cpu="$(tvp_tui_input 'CPU max per box (misal 1, 2):' '1')"
    [ -z "${ram}" ] && ram="512MB"
    [ -z "${cpu}" ] && cpu="1"

    tvp_step "Menyiapkan Caddy + DNS (${domain})..."
    tvp_setup_dns "${domain}"
    tvp_setup_caddy "${domain}"

    # Copy bundled catalog into state dir so the create menu is populated
    mkdir -p "${TVP_STATE}/services" "${TVP_STATE}/stacks"
    cp -n "${TVP_LIB}"/../services/*.tavp.sh "${TVP_STATE}/services/" 2>/dev/null || true
    cp -n "${TVP_LIB}"/../stacks/*.tavp.sh "${TVP_STATE}/stacks/" 2>/dev/null || true

    mkdir -p "${TVP_STATE}/boxes"
    cat > "${TVP_CONFIG}" <<EOF
# tavpbox config — generated by 'tavpbox init'
TVP_BASE_DISTRO="${distro}"
TVP_DOMAIN="${domain}"
TVP_LIMIT_RAM="${ram}"
TVP_LIMIT_CPU="${cpu}"
TVP_OS="${os}"
EOF
    tvp_ok "Config disimpan: ${TVP_CONFIG}"
    tvp_bold ""
    tvp_bold "tavpbox siap! Lanjut:  tavpbox create"
}

# ── create ───────────────────────────────────────────────────
tvp_cmd_create() {
    local fromfile=""
    while [ $# -gt 0 ]; do
        case "$1" in
            --from) fromfile="$2"; shift 2 ;;
            *) shift ;;
        esac
    done

    local name stack phalcon services hostpath
    if [ -n "${fromfile}" ]; then
        tvp_load_yaml "${fromfile}"
        name="${TVP_YML_name}"; stack="${TVP_YML_stack}"; phalcon="${TVP_YML_phalcon}"
        services="${TVP_YML_services}"; hostpath="${TVP_YML_path}"
    else
        name="$(tvp_tui_input 'Nama box (project1):' 'project1')"
        [ -z "${name}" ] && name="project1"
        stack="$(tvp_tui_select 'Stack:' tavp laravel symfony wordpress python node go blank)"
        [ -z "${stack}" ] && stack="tavp"
        phalcon=""
        if [ "${stack}" = "tavp" ]; then
            local p; p="$(tvp_tui_input 'Phalcon version (kosong = tidak):' '5.16')"
            phalcon="${p}"
        fi
        mkdir -p "${TVP_STATE}/services"
        local svc_list=()
        for f in "${TVP_STATE}"/services/*.tavp.sh; do
            [ -f "$f" ] || continue
            source "$f"
            svc_list+=("${TVP_NAME}")
        done
        services="$(tvp_tui_check 'Pilih services:' "${svc_list[@]}")"
        hostpath="$(tvp_tui_input 'Folder project (jadi webroot):' "$(pwd)")"
    fi

    tvp_step "Membuat box '${name}' dari ${TVP_BASE_DISTRO}..."
    local image; image="$(tvp_distro_image "${TVP_BASE_DISTRO}")"
    tvp_spin "lxc launch ${image}" lxc launch "${image}" "${name}"

    tvp_spin "Set limit RAM ${TVP_LIMIT_RAM}" lxc config set "${name}" limits.memory "${TVP_LIMIT_RAM}"
    tvp_spin "Set limit CPU ${TVP_LIMIT_CPU}" lxc config set "${name}" limits.cpu "${TVP_LIMIT_CPU}"

    # Folder mapping (Lando-style): host folder -> /var/www/html
    if [ -n "${hostpath}" ] && [ -d "${hostpath}" ]; then
        tvp_spin "Map folder ${hostpath}" \
            lxc config device add "${name}" www disk "source=${hostpath}" path=/var/www/html
    fi

    # Apply stack
    tvp_apply_stack "${name}" "${stack}" "${phalcon}" "${TVP_BASE_DISTRO}"

    # Apply services
    for s in ${services}; do
        tvp_apply_service "${name}" "${s}" "${TVP_BASE_DISTRO}"
    done

    # Save box state
    mkdir -p "$(tvp_box_dir "${name}")"
    cat > "$(tvp_box_dir "${name}")/box.conf" <<EOF
TVP_NAME="${name}"
TVP_STACK="${stack}"
TVP_PHALCON="${phalcon}"
TVP_SERVICES="${services}"
TVP_DISTRO="${TVP_BASE_DISTRO}"
TVP_PATH="${hostpath}"
TVP_DOMAIN="${name}.${TVP_DOMAIN}"
EOF

    # Wire Caddy + DNS
    tvp_caddy_add_box "${name}" "$(tvp_box_ip "${name}")" "${services}"
    tvp_dns_reload

    tvp_ok "Box '${name}' jalan di http://${name}.${TVP_DOMAIN}"
    [ -n "${services}" ] && echo "    Mail: http://mail.${name}.${TVP_DOMAIN}"
}

# ── start / stop / rebuild / etc ─────────────────────────────
tvp_cmd_start() {
    local n="$1"; [ -z "$n" ] && { tvp_error "nama box?"; exit 1; }
    tvp_spin "start ${n}" lxc start "${n}"
    tvp_caddy_add_box "${n}" "$(tvp_box_ip "${n}")" "$(tvp_box_services "${n}")"
    tvp_ok "http://${n}.${TVP_DOMAIN}"
}

tvp_cmd_stop() {
    local n="$1"; [ -z "$n" ] && { tvp_error "nama box?"; exit 1; }
    tvp_caddy_remove_box "${n}"
    tvp_spin "stop ${n}" lxc stop "${n}"
    tvp_ok "Box ${n} dihentikan (RAM bebas)"
}

tvp_cmd_rebuild() {
    local n="$1"; [ -z "$n" ] && { tvp_error "nama box?"; exit 1; }
    local svcs; svcs="$(tvp_box_services "${n}")"
    tvp_spin "rebuild ${n}" lxc rebuild "${n}" 2>/dev/null || {
        lxc stop "${n}" 2>/dev/null || true
        lxc start "${n}"
    }
    tvp_caddy_add_box "${n}" "$(tvp_box_ip "${n}")" "${svcs}"
    tvp_ok "Box ${n} direbuild, data tetap"
}

tvp_cmd_list() {
    lxc list
}

tvp_cmd_mail() {
    local n="$1"; [ -z "$n" ] && { tvp_error "nama box?"; exit 1; }
    local url="http://mail.${n}.${TVP_DOMAIN}"
    tvp_log "Buka: ${url}"
    command -v xdg-open >/dev/null && xdg-open "${url}" 2>/dev/null \
        || command -v open >/dev/null && open "${url}" 2>/dev/null \
        || echo "${url}"
}

tvp_cmd_ssh() {
    local n="$1"; [ -z "$n" ] && { tvp_error "nama box?"; exit 1; }
    lxc exec "${n}" -- bash
}

tvp_cmd_destroy() {
    local n="$1"; [ -z "$n" ] && { tvp_error "nama box?"; exit 1; }
    lxc delete "${n}" --force
    rm -rf "$(tvp_box_dir "${n}")"
    tvp_caddy_remove_box "${n}"
    tvp_ok "Box ${n} dihapus"
}

tvp_cmd_snapshot() {
    local n="$1"; [ -z "$n" ] && { tvp_error "nama box?"; exit 1; }
    local snap="snap-$(date +%Y%m%d-%H%M%S)"
    tvp_spin "snapshot ${n}" lxc snapshot "${n}" "${snap}"
    tvp_ok "Snapshot ${snap} dibuat"
}

# Read services list from a box's saved conf
tvp_box_services() {
    local f="$(tvp_box_dir "$1")/box.conf"
    [ -f "${f}" ] && grep '^TVP_SERVICES=' "${f}" | cut -d'"' -f2
}
